defaults:
  - scope:
      type: categories
    values:
      layout: category
      permalink: categories/:category/
  
  - scope:
      type: tags
    values:
      layout: tag
      permalink: tags/:tag/
